title:              Jeff Camacho
email:              jeff.d.camacho@gmail.com
description:        A Bootsrapped Blog for Projects and Life
author:             Jeff Camacho
baseurl:            "/jeff-blog"
url:                "https://www.jeffcamacho.com"

# Social Profiles
twitter_username:   jeff_mos_def
github_username:    jeff_mos_def
facebook_username:  
instagram_username: jeff_mos_def 
linkedin_username:  jeff-camacho

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
